name: snake_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - gymnasium==1.0.0
      - torch
      - stable-baselines3==2.9.0
      - pygame
      - gridmind==0.0.7
      - tqdm
      - tensorboard